
import pygame
import sys
import random

# אתחול של pygame
pygame.init()

# הגדרת רוחב וגובה החלון
WIDTH, HEIGHT = 800, 600
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("משחק יריות פרי נגד אויבים")

# צבעים
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# תמונות
player1_fruit = pygame.image.load("apple.png")  # תמונה של תפוח עבור שחקן 1
player2_fruit = pygame.image.load("banana.png")  # תמונה של בננה עבור שחקן 2
enemy_image = pygame.image.load("enemy.png")  # תמונה של אויב

# יצירת שחקן 1 (פרי או ירק)
player_width, player_height = 50, 50
player1 = pygame.Rect(WIDTH // 4 - player_width // 2, HEIGHT - player_height - 10, player_width, player_height)

# יצירת שחקן 2 (פרי או ירק)
player2 = pygame.Rect(3 * WIDTH // 4 - player_width // 2, HEIGHT - player_height - 10, player_width, player_height)

# יצירת ירי
bullet_width, bullet_height = 5, 10
bullets1 = []
bullets2 = []

# יצירת אויבים
enemies = []

# הגדרת מהירות
player_speed = 5
bullet_speed = 7
enemy_speed = 2

# הגדרת הצורות
player1_shape = "fruit"  # או "vegetable"
player2_shape = "vegetable"  # או "fruit"

# פונקציה לציור השחקן
def draw_player(player, shape):
    if shape == "fruit":
        screen.blit(player1_fruit, player)  # תפוח או פרי אחר
    elif shape == "vegetable":
        pygame.draw.rect(screen, (0, 255, 0), player)  # חסה או ירק אחר

# פונקציה לציור היריות
def draw_bullets():
    for bullet in bullets1:
        pygame.draw.rect(screen, WHITE, bullet)
    for bullet in bullets2:
        pygame.draw.rect(screen, WHITE, bullet)

# פונקציה לציור אויבים
def draw_enemies():
    for enemy in enemies:
        screen.blit(enemy_image, enemy)

# פונקציה להזיז את השחקן
def move_player(keys, player, player_num):
    if player_num == 1:
        if keys[pygame.K_LEFT] and player.left > 0:
            player.x -= player_speed
        if keys[pygame.K_RIGHT] and player.right < WIDTH // 2:
            player.x += player_speed
    if player_num == 2:
        if keys[pygame.K_a] and player.left > WIDTH // 2:
            player.x -= player_speed
        if keys[pygame.K_d] and player.right < WIDTH:
            player.x += player_speed

# פונקציה לירי
def shoot_bullet(player, bullets, player_num):
    bullet = pygame.Rect(player.centerx - bullet_width // 2, player.top, bullet_width, bullet_height)
    bullets.append(bullet)

# עדכון היריות
def update_bullets():
    for bullet in bullets1[:]:
        bullet.y -= bullet_speed
        if bullet.bottom < 0:
            bullets1.remove(bullet)
    for bullet in bullets2[:]:
        bullet.y -= bullet_speed
        if bullet.bottom < 0:
            bullets2.remove(bullet)

# עדכון אויבים
def update_enemies():
    global enemies
    for enemy in enemies[:]:
        enemy.y += enemy_speed
        if enemy.top > HEIGHT:
            enemies.remove(enemy)

# יצירת אויב חדש כל 2 שניות
def spawn_enemy():
    if random.randint(1, 100) > 98:  # 2% סיכוי להופיע אויב
        enemy = pygame.Rect(random.randint(50, WIDTH - 50), 0, 50, 50)
        enemies.append(enemy)

# חישוב קרבות
def check_collisions():
    global enemies, bullets1, bullets2
    # שחקן 1 נגד אויבים
    for bullet in bullets1[:]:
        for enemy in enemies[:]:
            if bullet.colliderect(enemy):
                bullets1.remove(bullet)
                enemies.remove(enemy)
                print("שחקן 1 הרג אויב")
    # שחקן 2 נגד אויבים
    for bullet in bullets2[:]:
        for enemy in enemies[:]:
            if bullet.colliderect(enemy):
                bullets2.remove(bullet)
                enemies.remove(enemy)
                print("שחקן 2 הרג אויב")

# לולאת המשחק
clock = pygame.time.Clock()

while True:
    screen.fill(BLACK)  # צבע הרקע של המסך

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
        if event.type == pygame.MOUSEBUTTONDOWN:
            if event.button == 1:  # לחיצה על כפתור עכבר שמאלי
                shoot_bullet(player1, bullets1, 1)
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_SPACE:
                shoot_bullet(player2, bullets2, 2)

    # קבלת מקשי חצים להזיז את השחקן
    keys = pygame.key.get_pressed()
    move_player(keys, player1, 1)
    move_player(keys, player2, 2)

    # עדכון היריות
    update_bullets()
    
    # עדכון אויבים
    update_enemies()

    # יצירת אויבים
    spawn_enemy()

    # חישוב התנגשות
    check_collisions()

    # ציור השחקנים, היריות והאויבים
    draw_player(player1, player1_shape)
    draw_player(player2, player2_shape)
    draw_bullets()
    draw_enemies()

    pygame.display.flip()  # עדכון המסך

    clock.tick(60)  # הגבלת FPS ל-60
  
